name: Contentful to GitHub Pages

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual triggering

jobs:
  fetch-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Use the version you need

      - name: Install dependencies
        run: npm install

      - name: Fetch content from Contentful
        run: |
          node scripts/fetchContentful.js

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs-content/*.mdx
          git commit -m "Update content from Contentful" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push origin main # Change 'main' to your default branch if different

  deploy:
    runs-on: ubuntu-latest
    needs: fetch-content
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-content # Change to your output directory
